version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: template-db
    environment:
      POSTGRES_USER: template
      POSTGRES_PASSWORD: template
      POSTGRES_DB: template
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U template -d template"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:8.3
    container_name: template-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - db

  app-runner:
    build:
      context: ../..
      dockerfile: docker/app/Dockerfile
    image: makotarifa/spring-boot-3-template-java-21:latest
    container_name: template-app-runner
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/template
      - SPRING_DATASOURCE_USERNAME=template
      - SPRING_DATASOURCE_PASSWORD=template
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:
    driver: local

networks:
  default:
    name: template_network
