spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/template
    username: template
    password: template
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration,classpath:db/dev

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/.well-known/jwks.json
      client:
        registration:
          demo:
            client-id: ${SPRING_SECURITY_OAUTH2_CLIENT_ID:demo-client}
            client-secret: ${SPRING_SECURITY_OAUTH2_CLIENT_SECRET:}
            authorization-grant-type: client_credentials
            scope: read,write

app:
  security:
    enabled: true
    cors:
      allowed-origins: "http://localhost:3000"
    cookie:
      secure: false
      same-site: Lax

server:
  port: 8080

logging:
  level:
    '[com.angelmorando.template]': DEBUG
