spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/template
    username: template
    password: template
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/.well-known/jwks.json
      client:
        registration:
          demo:
            client-id: demo-client
            client-secret: demo-secret
            authorization-grant-type: client_credentials
            scope: read,write

app:
  security:
    enabled: true

server:
  port: 8080

logging:
  level:
    com.angelmorando.template: DEBUG
